### ISSUE TITLE
nREPL server may hang on exit due to client connections remaining open

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#1002]
This issue is annoying because pressing `Ctrl-C` on the command line to exit requires manually closing the client connection. The server becomes unresponsive, necessitating a forceful termination of the client connection

To reproduce
1. run the nREPL server from the command line
```bash
> poetry run basilisp nrepl-server
nREPL server started on port 55156 on host 127.0.0.1 - nrepl://127.0.0.1:55156
```
2. Open a connection to the server
3.  Press Ctrl+C to stop it, it does not exit
```bash
> poetry run basilisp nrepl-server
nREPL server started on port 55156 on host 127.0.0.1 - nrepl://127.0.0.1:55156
Exiting in response to a keyboard interrupt...
```

You will need to forcefully close the connection on the client:
``` bash
> poetry run basilisp nrepl-server
nREPL server started on port 55156 on host 127.0.0.1 - nrepl://127.0.0.1:55156
Exiting in response to a keyboard interrupt...
(basilisp) PS C:\src\basilisp>
```

PR to follow

**Comment by chrisrink10** [comment]
Fixed by #1003
