### ISSUE TITLE
macro import references not resolved accross namespaces

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#1084]
Hi, 

(apologies if this was raised before. It seems familiar to me, but can't seem to find a reference)

It appears that using `import`ed references in a macro, when called from another namespace, results in an error

```
error occurred during macroexpansion: unable to resolve static or class member 'time/time' in this context
```

To reproduce,
Open the REPL, create a macro that uses an `import`ed symbol, switch to an`other` namespace, and try to call the macro. an unable to resolve error occurs.
```clojure
> basilisp repl
basilisp.user=> (import time)
<module 'time' (built-in)>

basilisp.user=> (defmacro it [] `(time/time))
#'basilisp.user/it

basilisp.user=> (it)
1728678698.2713509

basilisp.user=> (ns other)
nil

other=> (basilisp.user/it)

  exception: <class 'basilisp.lang.compiler.exception.CompilerException'> from <class 'basilisp.lang.compiler.exception.CompilerException'>
      phase: :macroexpansion
    message: error occurred during macroexpansion: unable to resolve static or class member 'time/time' in this context
       form: (basilisp.user/it)
   location: <REPL Input>:1
```

However, it works if the `import` with the same name is called in the `other` namespace:
```clojure
other=> (import time)
<module 'time' (built-in)>

other=> (basilisp.user/it)
1728678831.9680097
```

The same holds true for aliased imports.

It seems like `import`s used in a macro aren’t resolved in the calling namespace, unlike how `require` reference in a macro work. The expectation is that the `import` references in the macro should resolve to the module they were initially imported from.

Thanks

**Comment by chrisrink10** [comment]
This is not possible to do with imported names which must be linked as in Python (e.g. the import name must be available within the generated module to reference). For `require`s, Basilisp can use Var indirection to find the referenced name.

You must wrap the imported name in a non-private `def` or `defn` if you want to do something like this. See [`timed`](https://github.com/basilisp-lang/basilisp/blob/main/src/basilisp/core.lpy#L4042-L4055) for an example.

**Comment by chrisrink10** [comment]
I'm requesting to close this because it's not easily fixed (if it can be fixed at all). The code is effectively being inlined into the calling namespace and there is no way in Python (or Basilisp) to resolve that import name if it's not already defined in the module. Python and Java simply work differently in this regard (where in Java a name can be fully qualified and referenced from anywhere so long as that name is public).

**Comment by ikappaki** [comment]
> I'm requesting to close this because it's not easily fixed (if it can be fixed at all). The code is effectively being inlined into the calling namespace and there is no way in Python (or Basilisp) to resolve that import name if it's not already defined in the module. Python and Java simply work differently in this regard (where in Java a name can be fully qualified and referenced from anywhere so long as that name is public).

Thanks for having a look. As far as I'm concerned, this can be closed. The workaround shown in `timed` is workable and a much better solution than I was considering to have the referencing namespace import all the modules used by the macro.
