### ISSUE TITLE
can't reference unaliased import modules with dashes in their name

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#1085]
Hi,

it appears that referencing an unaliased `import`ed name with dashes instead of underscores in their name is not possible
```
unable to resolve symbol 'tests.a-b.b/B' in this context
```

To reproduce
1. In the `tests` directory create a subdirectory with underscore in its name, and inside it create a python file with a constant variable
**tests/a_b/b.py**
```python
B = 8
```
2. Open up a REPL, import that module and try to reference the variable using `-` for `_`, an unresolved symbol error is raised
```clojure
> basilisp repl
basilisp.user=> (import tests.a-b.b)
<module 'tests' from 'D:\\bas\\issue-rich\\tests\\__init__.py'>

basilisp.user=> tests.a-b.b/B

  exception: <class 'basilisp.lang.compiler.exception.CompilerException'>
      phase: :analyzing
    message: unable to resolve symbol 'tests.a-b.b/B' in this context
       form: tests.a-b.b/B
   location: <REPL Input>:1
```

The same works if an underscore `_` is used instead to reference the module
```clojure
basilisp.user=> tests.a_b.b/B
8
```

Thanks

**Comment by chrisrink10** [comment]
Confirming this is a bug. I'm not able to push a fix right now, but it's a fairly simple fix.

**Comment by ikappaki** [comment]
> Confirming this is a bug. I'm not able to push a fix right now, but it's a fairly simple fix.

Thanks. It's of no consequence since there is a simple workaround.
