### ISSUE TITLE
Symbols (and keywords) may not contain the `:` character

### ISSUE THREAD

**Issue by olavfosse** [basilisp-lang/basilisp#1105]
Congrats on the 0.3.0 release! I got right to work porting my https://github.com/olavfosse/context to basilisp and encountered two bugs in the process.

1. Symbols containing a `:` are split into a symbol followed by a keyword. In basilisp `(= ['a:b] ['a :b])`, in JVM clojure `(= ['a:b] [(symbol "a:b")])`.
2. Basilisp crashes on expressions such as:
```clj
#?(:clj (java.util.LinkedList/.addFirst ml x)
       :lpy (.appendleft ml x))
```
It complains that
> Symbols starting with '.' may not have a namespace

This should be allowed within :clj expressions at least.

Aside from that all seems to be working great. I did a search and replace from `java.util.LinkedList` to `java_util_LinkedList`, and after that all my tests passed in Basilisp!

Thanks!

With friendly regards

Olav

**Comment by olavfosse** [comment]
Fwiw I can just use the old syntax where the class is omitted: `(.addFirst ml x)`

Now all is working for me at least :^)

<img width="766" alt="image" src="https://github.com/user-attachments/assets/bf23adff-99c5-4926-a016-5d8b715154f1">

**Comment by chrisrink10** [comment]
> It complains that
> 
>  >   Symbols starting with '.' may not have a namespace
> 
> This should be allowed within :clj expressions at least.

This isn't specifically prohibited in Basilisp -- it's just a new feature in Clojure 1.12 I haven't gotten around to adding yet, so maybe this will be the impetus for doing so 😄 

Thanks for the report and glad you were able to get this tool working with Basilisp!

**Comment by chrisrink10** [comment]
I've split out the qualified method references into #1109 so I'm going to use this ticket to track the bug with symbols (and apparently keywords) not allowing the `:` symbol in the name.
