### ISSUE TITLE
inconsistent keywordization of strings containing slashes

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#1131]
Hi,

there appears to be an issue when trying to keywordizing strings containing slashes, such as "abc/xyz". These string don't compare equal to their corresponding namespaced keywords, even though their string representation match.

To reproduce
- Open up the REPL, create a keywordize slashed string, compare it with its counterpart and inspect it, it fails the check
```clojure
basilisp.user=> (def issuekw (keyword "abc/xyz"))
#'basilisp.user/issuekw

basilisp.user=> issuekw
:abc/xyz

basilisp.user=> (= issuekw :abc/xyz)
false

basilisp.user=> (namespace issuekw)
nil

basilisp.user=> (name issuekw)
"abc/xyz"
```

In clojure comparison works as expected, comparing equal with their counterparts, internally the string to a namespace and name components
```clojure
user=> (def issuekw (keyword "abc/xyz"))
#'user/issuekw
user=>  issuekw
:abc/xyz
user=> (= issuekw :abc/xyz)
true
user=> (namespace issuekw)
"abc"
user=> (name issuekw)
"xyz"
```

Thanks

**Comment by chrisrink10** [comment]
😓 This is completely undocumented behavior on the part of Clojure and really seems like something they _shouldn't_ allow. The fix is straightforward enough though.

I'll just also note that the way it works in Clojure still can have some surprising results:

```clojure
((juxt namespace name) (keyword "abc/def/xyz"))  ;;=> ["abc" "def/xyz"]
```

**Comment by ikappaki** [comment]
Thanks for the fix!

> 😓 This is completely undocumented behavior on the part of Clojure and really seems like something they _shouldn't_ allow. The fix is straightforward enough though.
> 
> I'll just also note that the way it works in Clojure still can have some surprising results:
> 
> ```clojure
> ((juxt namespace name) (keyword "abc/def/xyz"))  ;;=> ["abc" "def/xyz"]
> ```

Indeed. IMO it gets even stranger because it allows any illegal character to be part of the keyword name, which I think it does break reading the form back completely (example below is in Clojure)

```clojure
user=> (keyword "^#{[abc")
:^#{[abc
user=> (keyword "")
:
```
