### ISSUE TITLE
clojure compatibility: anonymous functions in syntax-quote

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#1160]
Hi,

there is a small descrepancy when it comes to expanding anonymous functions in syntax-quotes. Clojure expands it it as a function defintion while Basilisp does not.

To reproduce syntax-unquote an anonymous function in both Basilisp and Clojure

In Clojure
```clojure
`#(println %)
(fn* [p1__24__25__auto__] (clojure.core/println p1__24__25__auto__))
```

In Basilisp
```clojure
`#(println %)
(fn* [] (basilisp.core/println basilisp.user/%))
```

It is not clear from the https://clojure.org/reference/reader#syntax-quote documentation that this should be the case though, but this appears to be the reality. Anonymous function doc https://clojure.org/guides/weird_characters#_anonymous_function, 

Thanks

**Comment by chrisrink10** [comment]
Good catch! Got a fix coming up.
