### ISSUE TITLE
Issue with calling a macro that defines a multiarity function

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#1163]
Hi,

there appears to be an issue with calling a macro that defines a multiarity function
```error occurred during macroexpansion: Expected an argument vector {:found ([] 5)}```

To reproduce, open up the REPL and call the macro defining the multiarity function
```clojure
> basilisp repl
basilisp.user=> (defmacro issue [] `(defn y ([] 5)))
#'basilisp.user/issue

basilisp.user=> (issue)

  exception: <class 'basilisp.lang.exception.ExceptionInfo'> from <class 'basilisp.lang.compiler.exception.CompilerException'>
      phase: :macroexpansion
    message: error occurred during macroexpansion: Expected an argument vector {:found ([] 5)}
       form: (basilisp.core/defn basilisp.user/y ([] 5))
   location: <REPL Input>:1
```

The same works in Clojure as expected
```clojure
> clj
Clojure 1.7.0
user=> (defmacro issue [] `(defn y ([] 5)))
#'user/issue
user=> (issue)
#'user/y
user=> (y)
5
```

Thanks

**Comment by chrisrink10** [comment]
Think #1164 ought to fix it. I had a few uses of `list?` where `seq?` is typically used in Clojure. `list?` often is wrong when dealing with the results of a syntax quote.

Unrelated comment/question: I see you're using quite an old version of Clojure 👀  -- any reason for that?

**Comment by ikappaki** [comment]
> Think #1164 ought to fix it. I had a few uses of `list?` where `seq?` is typically used in Clojure. `list?` often is wrong when dealing with the results of a syntax quote.

Thanks for looking into this!

> Unrelated comment/question: I see you're using quite an old version of Clojure 👀 -- any reason for that?

Just laziness 😅 I happen to have a terminal open in the `hiccup` checkout dir, and the source `deps.edn` there specifies Clojure 1.7 as a dep.
