### ISSUE TITLE
Any thoughts about making it compatible with Mojo language?

### ISSUE THREAD

**Issue by bhougland18** [basilisp-lang/basilisp#701]
I am just leaving this here incase you aren't aware, but there is a new language that is a superset of python that is optimized for speed and parallelism called Mojo.  See this link for more information: https://www.youtube.com/watch?v=ng438SIXyW4.  Didn't know if it would be possible to target both, or Mojo as the primary once it matures.

**Comment by chrisrink10** [comment]
Hi @bhougland18. I was not aware of Mojo before this. I don't want to say that we'll never implement a backend based on Mojo, but it does seem unlikely to me. That said, the reason that the compiler is de-coupled into an analyzer and a separate code generator is to allow for the possibility of different compilation targets.
