### ISSUE TITLE
support for scientific and hexadecimal numeric literals

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#769]
While Clojure supports scientific (e.g. 2e6) and hex literals (e.g. 0xFACE), `basilisp` currently lacks this functionality
to reproduce.

1. Open up a REPL and type in example literals for each
``` clojure
basilisp.user=> 2e6
Traceback (most recent call last):
...
    raise AnalyzerException(
basilisp.lang.compiler.exception.CompilerException: unable to resolve symbol 'e6' in this context {:form e6 :phase :analyzing}

basilisp.user=> 0xFACE
Traceback (most recent call last):
...
    raise AnalyzerException(
basilisp.lang.compiler.exception.CompilerException: unable to resolve symbol 'xFACE' in this context {:form xFACE :phase :analyzing}
```

contrast with Clojure
``` clojure
user> 2e6
2000000.0
user> 0xFACE
64206
```

Is there any interest supporting them? Users can always use the standard notation otherwise.

Thanks

**Comment by chrisrink10** [comment]
Yes, I think that makes sense to add support for this. Python also natively supports this syntax.
