### ISSUE TITLE
destructuring support for `for` loops

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#774]
Clojure supports destructuring in for loops, but `basilisp` explicitly doesn't do so
```
for expression bindings must start with symbol binding
```

from the`for` docstring
``` 
... Symbol bindings look like standard ``let`` bindings without destructuring ...
```

to reproduce
1. Open up the REPL and type in a simple `for` loop whose binding is destructured
``` clojure
basilisp.user=> (for [[a b] [[1 2]]] (+ a b))
Traceback (most recent call last):
  File "/src/basilisp/src/basilisp/lang/compiler/analyzer.py", line 2436, in _invoke_ast
    expanded = fn.var.value(macro_env, form, *form.rest)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/core.lpy", line 3543, in for_
    (throw (ex-info "for expression bindings must start with symbol binding"
basilisp.lang.exception.ExceptionInfo: for expression bindings must start with symbol binding {:bindings [[a b] [[1 2]]]}
...
```

to contrast with clojure
``` clojure
user> (for [[a b] [[1 2]]] (+ a b))
(3)
```

I find this to be a very useful feature, any reason why this is not supported, perhaps a remnant of the past?

thanks

**Comment by chrisrink10** [comment]
I don't know for sure. I would guess that I decided it was not something I had ever used and the definition of `for` was already complex enough, so I decided to omit it.
