### ISSUE TITLE
typing_extension supported versions range

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#809]
Hi,

would it be possible to extend the `typing_extensions` version coverage to begin at 4.7 so as to support environments constrained on at least that version.

e.g.

``` toml
typing_extensions = "^4.7.0"
```

It is currently set to `^4.9.0`. I've tested this to work with 4.7.0 and pytests pass, though I'm not sure if this can have any diverse impact at runtime (I assume there is none).

Thanks

**Comment by chrisrink10** [comment]
Can you give me more information as to why this is necessary or useful?

**Comment by chrisrink10** [comment]
Fixed in #827
