### ISSUE TITLE
`*flush-on-newline*` support

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#865]
The Clojure's *flush-on-newline* indicates whether to flush the out stream at the end of  `core/prn` fn, which is also the base for `println`.

This is a useful  feature to have when the stream is bound to anything else than `stdout` which is already configured to flush its output buffer on newlines by default.

PR to follow.

**Comment by ikappaki** [comment]
Hi @chrisrink10,

any chance you could push out the next Basilisp release? I'm planning to make a PR to CIDER to support `jack-in` to Basilisp by having CIDER invoke `basilsp nrepl-server`. However, I noticed that the nREPL host and port string are not flushed to stdout on MS-Windows, which prevents Emacs CIDER identifying when the server is up and running, it works fine on Linux and MacOs otherwise. It requires this feature to flush stdout out on newline, which is not officially released yet.

Thanks

**Comment by chrisrink10** [comment]
I released v0.1.0b2
