### ISSUE TITLE
 *warn-on-reflection* support

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#881]
Hi,

is [reflection checking at runtime](https://clojure.org/reference/java_interop#typehints) relevant in Basilisp, and if so, how difficult would it be to implement the `*warn-on-reflection` dynamic var to warn of such instances at compile time?

I'm only asking because `clojure.pprint` does sets this flag at the top while there are many typehints set in the code.

Thanks

**Comment by chrisrink10** [comment]
`*warn-on-reflection*` is not needed in Basilisp. Basilisp has other [warnings](https://basilisp.readthedocs.io/en/latest/compiler.html#warnings) which cover similar cases, but which are generally set per-session. [Type hints](https://basilisp.readthedocs.io/en/latest/pyinterop.html#type-hinting) are not used by the compiler at all in Basilisp.
