### ISSUE TITLE
dots in keywords

### ISSUE THREAD

**Issue by FalseProtagonist** [basilisp-lang/basilisp#899]
basilispp throws on dots in keywords, but they are widely used, eg. in Datomic:

https://docs.datomic.com/schema/schema-reference.html

**Comment by chrisrink10** [comment]
Hi and thanks for the report.

In the linked document I only see Datomic using `.` characters in namespaced keywords which Basilisp supports:

```
basilisp.user=> :db.cardinality/one
:db.cardinality/one
```

On the other hand, Basilisp does not _read_ keywords containing `.` characters in the name portion which matches Clojure's [documentation](https://clojure.org/reference/reader#_literals).

It seems they [eventually allowed `.` characters in keywords and never updated the documentation](https://clojure.atlassian.net/browse/CLJ-889), so I guess we need to relax this for Basilisp.

**Comment by NoahTheDuke** [comment]
They're also widely used in [honeysql](https://github.com/seancorfield/honeysql) and [hiccup](https://github.com/weavejester/hiccup) and similar libraries. Sadly, the cat's out of the bag on this one.

**Comment by FalseProtagonist** [comment]
Sorry, my example wasn't the best one. I hadn't realized the namespaced-dots vs other-dots difference but as you/Noah noted the other brand does exist a lot in big libs in the wild.

**Comment by NoahTheDuke** [comment]
After I brought this up in Clojurian slack, Alex Miller has removed this line from the reference `"They cannot contain '.' in the name part, or name classes."`, so all periods are officially legal in keywords now.
