### ISSUE TITLE
calling keyword on a symbol different result from clojure

### ISSUE THREAD

**Issue by FalseProtagonist** [basilisp-lang/basilisp#911]
not sure what is the "right" behaviour

but in clojure I can call (keyword sym) inside a macro and it's all good

in basilisp, (keyword sym) sets the _name of the resulting Keyword to be an instance of Symbol

don't know whether this is right/intended but it caused me some macro errors that were tough to track down, because

:x and :x are not equal, and (evaluating I think) :x where it contains a symbol as _name exploded

**Comment by chrisrink10** [comment]
Please provide reproduction steps and errors (if any occurred).

**Comment by FalseProtagonist** [comment]
The error is buried in a macro I'd rather not publish, but the difference can be demonstrated by the result of the following fragment in clj vs lpy

(= (keyword 'x) (keyword "x"))

hope this is helpful, sorry I can't dig out the error without pasting a lot of proprietary code

the error (rather than merely a difference) seems to happen when (keyword 'x) occurs inside nested syntax quotes
