### ISSUE TITLE
reduce-kv different from clojure

### ISSUE THREAD

**Issue by FalseProtagonist** [basilisp-lang/basilisp#927]
This fails in :lsp, works in :clj:

`(reduce-kv  
   (fn [acc i v] (-> acc
    (update :ks conj i)
     (update :vs conj v)))   
   {:ks [] :vs []}   
   [:a :b :c])`

**Comment by chrisrink10** [comment]
Confirmed. Probably just need to do a `map-indexed` or something over the vector for now. This will require implementing a few new interfaces to support k/v reducing.
