### ISSUE TITLE
Altered Vars should resolve to their latest value.

### ISSUE THREAD

**Issue by mitch-kyle** [basilisp-lang/basilisp#969]
Vars aren't resolving to their current value after being altered. I tried this in the repl and with a script with the same result. Dynamic vars seem to be unaffected.

```clojure
;; 1. Create a var
basilisp.user=> (def foo 1)
#'basilisp.user/foo

basilisp.user=> foo
1

;; 2. Alter the var
basilisp.user=> (alter-var-root #'foo inc)
nil

;; We would expect to see the value 2 here
;; `foo` isn't reflecting changes to the var
basilisp.user=> foo
1

basilisp.user=> basilisp.user/foo
1

;; dereferencing the var `foo` does show the expected result.
basilisp.user=> @#'foo
2
```

**Comment by chrisrink10** [comment]
This is almost definitely due to [direct linking](https://basilisp.readthedocs.io/en/latest/compiler.html#direct-linking).

You can disable the behavior globally with a compiler flag or locally by marking the Var as `^:redef` when you def it.
